# Generated by Django 5.1.6 on 2026-02-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_id", models.CharField(max_length=50, unique=True)),
                ("capacity", models.IntegerField()),
                ("floor_no", models.IntegerField()),
                ("near_washroom", models.BooleanField(default=False)),
            ],
        ),
    ]
